# Generated by Django 5.2.6 on 2025-09-16 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_comment_movie_comment_watch_session_like_movie_and_more'),
        ('movies', '0002_moviefile_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
