# Generated by Django 5.2.6 on 2025-09-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_alter_comment_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
    ]
